package com.synexoit.weatherapplication.remote.entity.darksky

data class DailyDataRemote(var time: Long = 0,
                           var summary: String = "",
                           var placeId: String = "",
                           var icon: String = "",
                           var sunriseTime: Double = 0.0,
                           var sunsetTime: Double = 0.0,
                           var moonPhase: Double = 0.0,
                           var precipIntensity: Double = 0.0,
                           var precipIntensityMax: Double = 0.0,
                           var precipIntensityMaxTime: Double = 0.0,
                           var precipProbability: Double = 0.0,
                           var precipType: String = "",
                           var temperatureMin: Double = 0.0,
                           var temperatureMinTime: Double = 0.0,
                           var temperatureMax: Double = 0.0,
                           var temperatureMaxTime: Double = 0.0,
                           var apparentTemperatureMin: Double = 0.0,
                           var apparentTemperatureMinTime: Double = 0.0,
                           var apparentTemperatureMax: Double = 0.0,
                           var apparentTemperatureMaxTime: Double = 0.0,
                           var dewPoint: Double = 0.0,
                           var humidity: Double = 0.0,
                           var windSpeed: Double = 0.0,
                           var windBearing: Double = 0.0,
                           var cloudCover: Double = 0.0,
                           var pressure: Double = 0.0,
                           var ozone: Double = 0.0)

